services:
  postgres:
    image: postgres
    container_name: galeria_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: adminuser
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: GaleriaArte
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql  # 🔧 RUTA ADAPTADA
    networks:
      - galeria_net

volumes:
  pgdata:

networks:
  galeria_net: