global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # UsuarioService monitoring
  - job_name: 'usuario-service'
    static_configs:
      - targets: ['host.docker.internal:5002']  # Puerto actualizado según launchSettings.json
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  # ObraService monitoring
  - job_name: 'obra-service'
    static_configs:
      - targets: ['host.docker.internal:5003']  # Puerto del ObraService
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s
